### ISSUE TITLE
Always create the Pull Requests when promoting

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx-promote#74]
Following a discussion at the jx office hours - https://youtu.be/zv0Dn9RYzwE?t=2603 

How about changing the promotion "workflow" for jx v3, and always create a PR:
- for the environments in "auto" promotion, either merge the PR or set an "approved" label (so that lighthouse will merge it automatically)
- for the environments in "manual" promotion, create a PR, either in "draft" mode (github) or with specific labels so that it won't be merge automatically

the advantages of such a workflow:
- deploying to prod (which is an env in manual promotion mode) only requires to merge an existing PR. No need to run the `jx promote` cmd again.
- people can discuss the deployment in the PR
- people can add commits to the PR - for example extra values that might be required by the new version

we've been using this workflow at Dailymotion for a while now, and really like it. Here's how we're creating/updating the "prod" PRs:
- we use a specific label to identify the PR for a specific application in the prod-env git repo - such as `update-my-app`
- if there is no opened PR with such a label, create a new branch/PR with the update (and the changelog of the release in the body of the PR - this really helps)
- if there is an existing PR with such as label, checkout its branch, and update it with the new version, and push the branch - so we just update the existing PR. We also update the PR body to prepend the changelog for the new version, and we update the title to use the latest version
- these PRs are created in draft mode (in github)

the advantage of updating the existing PR/branch is that the following use-case works well:
- new version 1.2.3
- someone adds a commit to add a helm value for example
- new version 1.2.4
- merge => the new helm value is not lost
(previously we've been force-pushing the branch and erasing all previous commits, but it means that if you don't merge right away you might lose some changes)

**Comment by vbehar** [comment]
cc @jstrachan

**Comment by jstrachan** [comment]
@vbehar I love your approach and really want to implement this yes. I've actually been trying it out already btw ;) I had to fix a few gremlins to get it to create N promote PRs so getting close now...

The main missing part is the logic you describe; to create a PR if Manual (and use a draft). We'll need a minor patch to go-scm to allow draft PRs to be created.

Incidentally I've added a label of `env/staging` or `env/production` to the PR too so we can do different kinds of lighthouse merge rules (tide/keeper) to avoid production auto merging without the required approval labels or whatever.

**Comment by vbehar** [comment]
nice! I knew you wouldn't wait for the issue to start working on it :-)

**Comment by jstrachan** [comment]
;) - I do love the simplicity of this idea. So many folks have trouble running `jx promote` locally to do a promotion - plus its kinda risky guessing the version number to support etc. So creating a draft PR is so much cleaner.

**Comment by hervelemeur** [comment]
About the manual problem, does the addition of a "do-not-merge" label would do the trick without resorting to a specific github mecanism?

**Comment by jstrachan** [comment]
@hervelemeur great idea

**Comment by gazal-k** [comment]
While testing it, we found that it creates PRs with draft labels for additional envs (even if `promotionStrategy`  is `Auto`)

This: https://github.com/jenkins-x/jx-promote/pull/153 is an attempt at fixing that.

**Comment by gazal-k** [comment]
I think we can add another cli option `--all` which will target `Auto` as well as `Manual` envs unlike `--all-auto` which will only do `Auto` envs

**Comment by jstrachan** [comment]
we have `--all` now on `jx promote`

**Comment by jstrachan** [comment]
also this PR allows us to group multiple `Auto` environments in the same git repository in the same PRs (you can disable this behaviour with `--no-pr-group`)
https://github.com/jenkins-x/jx-promote/pull/216

**Comment by jstrachan** [comment]
see the docs: https://jenkins-x.io/v3/develop/environments/promotion/
